preview = true
unsafe-fixes = true
target-version = "py313"
line-length = 79
builtins = ["_"]
exclude = ["docs/conf.py", "tests/__init__.py"]

[analyze]
preview = true

[format]
preview = true
docstring-code-format = true
line-ending = "lf"
skip-magic-trailing-comma = true

[lint]
future-annotations = true
select = ["ALL"]
typing-extensions = false
unfixable = ["T201"]
ignore = [
    "D206",
    "E114",
    "E111",
    "W191",
    "Q003",
    "Q002",
    "Q000",
    "Q001",
    "COM812",
    "D208",
    "E117",
    "COM819",
    "D300",
    "D207",
    "Q004",
    "S404",
    "S602",
    "S603",
    "D203",
    "D212",
    "FBT001",
    "FBT002",
]

[lint.isort]
split-on-trailing-comma = false

[lint.extend-per-file-ignores]
"**/__init__.py*" = ["F403", "F401"]
"tests/**/*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG",  # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT",  # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
]
