from serial import Serial
from typing import Literal

command_line_flag: bool
SERIAL_BAUD_RATE: int

def find_microbit() -> tuple[str, str | None] | tuple[None, None]: ...
def raw_on(serial: Serial) -> None: ...
def raw_off(serial: Serial) -> None: ...
def get_serial(timeout: int = 10) -> Serial: ...
def execute(commands: list[str], serial: Serial | None = None, timeout: int = 10) -> tuple[Literal[''], bytes] | tuple[bytes, Literal['']]: ...
def clean_error(err: bytes) -> str: ...
def ls(serial: Serial | None = None, timeout: int = 10) -> list[str]: ...
def rm(filename: str, serial: Serial | None = None, timeout: int = 10) -> Literal[True]: ...
def put(filename: str, target: str | None = None, serial: Serial | None = None, timeout: int = 10) -> Literal[True]: ...
def get(filename: str, target: str | None = None, serial: Serial | None = None, timeout: int = 10) -> Literal[True]: ...
def version(serial: Serial | None = None, timeout: int = 10) -> dict[str, str]: ...
def main(argv: list[str] | None = None) -> None: ...
