# Copyright (c) 2026 Blackteahamburger <blackteahamburger@outlook.com>
#
# See the LICENSE file for more information.
class MicroBitError(RuntimeError): ...
class MicroBitNotFoundError(MicroBitError): ...
class MicroBitIOError(MicroBitError, OSError): ...
class MicroBitBaseException(MicroBitError, BaseException): ...
class MicroBitArithmeticError(MicroBitError, ArithmeticError): ...
class MicroBitAssertionError(MicroBitError, AssertionError): ...
class MicroBitAttributeError(MicroBitError, AttributeError): ...
class MicroBitEOFError(MicroBitError, EOFError): ...
class MicroBitException(MicroBitError, Exception): ...
class MicroBitGeneratorExit(MicroBitError, GeneratorExit): ...
class MicroBitImportError(MicroBitError, ImportError): ...
class MicroBitIndentationError(MicroBitError, IndentationError): ...
class MicroBitIndexError(MicroBitError, IndexError): ...
class MicroBitKeyboardInterrupt(MicroBitError, KeyboardInterrupt): ...
class MicroBitKeyError(MicroBitError, KeyError): ...
class MicroBitLookupError(MicroBitError, LookupError): ...
class MicroBitMemoryError(MicroBitError, MemoryError): ...
class MicroBitNameError(MicroBitError, NameError): ...
class MicroBitNotImplementedError(MicroBitError, NotImplementedError): ...
class MicroBitOSError(MicroBitError, OSError): ...
class MicroBitOverflowError(MicroBitError, OverflowError): ...
class MicroBitRuntimeError(MicroBitError, RuntimeError): ...
class MicroBitStopAsyncIteration(MicroBitError, StopAsyncIteration): ...
class MicroBitStopIteration(MicroBitError, StopIteration): ...
class MicroBitSyntaxError(MicroBitError, SyntaxError): ...
class MicroBitSystemExit(MicroBitError, SystemExit): ...
class MicroBitTypeError(MicroBitError, TypeError): ...
class MicroBitUnicodeError(MicroBitError, UnicodeError): ...
class MicroBitValueError(MicroBitError, ValueError): ...
class MicroBitZeroDivisionError(MicroBitError, ZeroDivisionError): ...
